blank_issues_enabled: true
contact_links:
  - name: 🧑‍🤝‍🧑 Community Discord
    url: https://discord.gg/6UyHPeGZAC
    about: Interact with the Mintplex Labs community here by asking for help, discussing and more!
